from Recommendation_System_Books.pipeline.training_pipeline import TrainingPipeline

training_pipeline = TrainingPipeline()
training_pipeline.start_data_ingestion()
training_pipeline.start_data_validation()
training_pipeline.start_training_pipeline()
training_pipeline.start_model_trainer()